name: Semgrep SQL Injection Scan

on:
  push:
    branches: [ "main","feat/admin" ]
  pull_request:
    branches: [ "main","feat/admin" ]

jobs:
  semgrep-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./semgrep.yml